### ISSUE TITLE
[vscode] 'ClassSymbol' object has no attribute 'get_module_symbol'

### ISSUE THREAD

**Issue by oyale** [odoo/odoo-ls#72]
**Your setup**
Version: 14.0
Operating System: Ubuntu
IDE and/or Integration tool: 
- `Vscode - official extension`

**Describe the bug**
When loading the configuration, it crashes complaining about `'ClassSymbol' object has no attribute 'get_module_symbol'`.

**Additional context**

- I'm running it in a VSCode connected to a remote server using the official extension `Remote SSH`.

Logs before crash:
```python
[INFO] Starting the extension.
[Trace - 4:19:06 PM] Sending request 'initialize - (0)'.
[Trace - 4:19:07 PM] Received response 'initialize - (0)' in 921ms.
[Trace - 4:19:07 PM] Sending notification 'initialized'.
[Trace - 4:19:07 PM] Sending notification 'Odoo/clientReady'.
[Trace - 4:19:07 PM] Sending notification 'textDocument/didOpen'.
[Trace - 4:19:07 PM] Sending notification 'textDocument/didOpen'.
[Trace - 4:19:07 PM] Received request 'client/registerCapability - (bd395843-5a5e-48a1-b392-79c96d900822)'.
[Trace - 4:19:07 PM] Sending response 'client/registerCapability - (bd395843-5a5e-48a1-b392-79c96d900822)'. Processing request took 0ms
[Trace - 4:19:07 PM] Received notification 'window/logMessage'.
Building new Odoo knowledge database
[Trace - 4:19:07 PM] Received request 'Odoo/getConfiguration - (ad1682bc-cced-48e4-b51a-502978ba8334)'.
[Trace - 4:19:07 PM] Sending response 'Odoo/getConfiguration - (ad1682bc-cced-48e4-b51a-502978ba8334)'. Processing request took 0ms
[Trace - 4:19:07 PM] Received request 'workspace/configuration - (7d4df00d-e7ac-46dc-a6f3-f106ed425374)'.
[Trace - 4:19:07 PM] Sending response 'workspace/configuration - (7d4df00d-e7ac-46dc-a6f3-f106ed425374)'. Processing request took 0ms
[Trace - 4:19:08 PM] Received notification 'Odoo/loadingStatusUpdate'.
[Trace - 4:19:09 PM] Received notification 'window/logMessage'.
Odoo version: 14.0.0
Missing addon paths : ["/opt/odoo_modules/test"]
[Trace - 4:19:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:19:24 PM] Received notification 'Odoo/displayCrashNotification'.
[Trace - 4:19:24 PM] Received notification 'window/logMessage'.
```

**Traceback:**
```python
Traceback (most recent call last):
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/core/odoo.py", line 156, in initialize
    Odoo.instance.build_database(ls, odooConfig)
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/core/odoo.py", line 200, in build_database
    if not self.build_base(ls, used_config):
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/core/odoo.py", line 230, in build_base
    self.process_rebuilds(ls)
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/core/odoo.py", line 359, in process_rebuilds
    validation.validate()
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/features/validation/python_validator.py", line 54, in validate
    self.validate_structure()
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/features/validation/python_validator.py", line 313, in validate_structure
    inherited_models = model.get_main_symbols(self.currentModule)
  File "/home/odoo/.vscode-server/extensions/odoo.odoo-0.2.1/server/core/model.py", line 22, in get_main_symbols
    if not from_module or not sym.get_module_symbol() or \
AttributeError: 'ClassSymbol' object has no attribute 'get_module_symbol'
 
```

**Comment by fda-odoo** [comment]
Thank you for your report, indeed a small typo was hidden in the last patch :'( It's fixed now ;)
